# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
    # check these on https://fabricmc.net/develop
    minecraft_base_version=1.21.11
    minecraft_version=1.21.11
    yarn_mappings=1.21.11+build.3
    loader_version=0.18.4

# Mod Properties
    mod_version = 0.2.5
    maven_group = io.wispforest
    archives_base_name = gadget

# Dependencies
    fabric_version=0.140.2+1.21.11
    owo_version=0.12.24+1.21.9
    modmenu_version=17.0.0-beta.1
    rei_version=20.0.811
    fabric_perms_api=0.5.0
    mapping_io=0.6.1
    auoeke_result=0.4.1
    auoeke_unsafe=1.7.3
    auoeke_reflect=6.3.0
    quiltflower=1.9.0
    auth_me=9.0.1+1.21.4
    cloth_config=20.0.149
